spring:
  profiles:
    active: dev
  application:
    name: Lock2
  data:
    redis:
      port: 6379
      host: localhost
  config:

    import: "optional:nacos:localhost:8848"

  cloud:
    config:
      import-check:
        enabled: false
    nacos:
      password: nacos
      username: nacos
#      config:
#        server-addr: localhost:8848
#        file-extension: yaml
#        group: DEFAULT_GROUP
#        prefix: ${spring.application.name}
#        secret-key: eyJsaWNlbnNlSWQiOiJZOU1YU0lGNzlHIiwibGljZW5zZWVOYW1lIjoiSkJGYW1pbHkgQ2hpbmEiLCJhc3NpZ25lZU5hbWUiOiIiLCJh
#        password: nacos
#        username: nacos

    sentinel:
      transport:
        dashboard: localhost:8088 # 配置Sentinel dashboard地址
        # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719

      # 添加 Nacos 数据源的配置
      datasource:
        flow-rules: #流控规则
          nacos:
            server-addr:  localhost:8848
            namespace: sentinel
            username: nacos
            password: nacos
            dataId: ${spring.application.name}-flow-rules
            group-id: DEFAULT_GROUP   # 注意groupId对应Sentinel Dashboard中的定义
            data-type: json
            rule-type: flow
        degrade-rules: #降级规则
          nacos:
            server-addr:  localhost:8848
            namespace: sentinel
            dataId: ${spring.application.name}-degrade-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade
            username: nacos
            password: nacos
        param-flow-rules:
          nacos:
            server-addr:  localhost:8848
            namespace: sentinel
            dataId: ${spring.application.name}-param-flow-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: param-flow
            username: nacos
            password: nacos
        authority-rules:
          nacos:
            server-addr:  localhost:8848
            namespace: sentinel
            dataId: ${spring.application.name}-authority-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: authority
            username: nacos
            password: nacos
        system-rules:
          nacos:
            server-addr:  localhost:8848
            namespace: sentinel
            dataId: ${spring.application.name}-system-rules
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: system
            username: nacos
            password: nacos


server:
  port: 8081

